### ISSUE TITLE
MM Exception concerning AnisotropicPartResizer and MultiAnimators

### ISSUE THREAD

**Issue by iGGnite** [allista/AT_Utils#11]
Hello, I recently encountered a bug with KerbalJointReinforcement and Lisias [came across some problems](https://forum.kerbalspaceprogram.com/index.php?/topic/50911-13-kerbal-joint-reinforcement-v333-72417/&do=findComment&comment=3587588) in my ksp.log (see below). I'm not quite sure which of my mods depend on AT_Utils so I can't really locate problems. Here is my mod list: 
![36c558535ab27d6c32986cd60b25706b](https://user-images.githubusercontent.com/36937528/56577607-adca6600-65cb-11e9-9926-175b0b59ef2a.png)
And here is my KSP.log: [KSP.log](https://github.com/allista/AT_Utils/files/3107252/KSP.log)
I hope this is of some value, tell me if you need anything else from me.

**Comment by allista** [comment]
This is an installation problem: you don't have the needed .dlls from AT_Utils. To fix it, install the appropriate version of the full AT_Utils from github: 
https://github.com/allista/AT_Utils/releases
