### ISSUE TITLE
Changing color values in 000_AT_Utils.glob has no effect on UI

### ISSUE THREAD

**Issue by alexandruast** [allista/AT_Utils#13]
Colorblind TCA user here.
It seems that no matter what colors I set in 000_AT_Utils.glob or .user, the changes are always the default ones.
Reverting to 1.6.3/3.5.3.2 in the meantime.

**Comment by allista** [comment]
Unfortunately I cannot support old KSP versions.

Currently you can change all the colors via dedicated UI available through the right-mouse-button click on the TCA app launcher button. The color scheme is shared between all my mods, so if you have Hangar or Global Construction, it works with their respective buttons as well.

The settings are saved in `GameData/000_AT_Utils/000_AT_Utils.user` and have the following format:
```
Colors
{
	Active = #FFE504FF
	Close = #FF3900FF
	Confirm = #00FF53FF
	Danger = #FF0000FF
	Enabled = #00FF60FF
	Good = #0DFF00FF
	Inactive = #808080FF
	Open = #00FF00FF
	Selected1 = #00FFFFFF
	Selected2 = #FF00FFFF
	Warning = #FFEB00FF
	Neutral = #FFFFFFFF
}
```
