### ISSUE TITLE
Failure to load in 1.8.1 with mechjeb

### ISSUE THREAD

**Issue by xaerogonzo** [allista/AT_Utils#15]
Getting the common hang on Verifying Expansion: Breaking ground SquadExpansion/Serenity.

I checked the logs and it listed AT_Utilis as the fault. Unfortunately, i don't have the log after removing it and since it takes about a while to load until breaking ground, i have not gotten around to doing it. But wanted to let you know asap of this problem and i will post new logs later today.

I have also not tried removing mechjeb with at active. Mechjeb seems to be a catalyst for many other mods not working including fire spitter

**Comment by Gordon-Dry** [comment]
Related?
https://github.com/MuMech/MechJeb2/commit/2ec50b610e63e048694374f9ed2cf8d2c372f79f

**Comment by allista** [comment]
> I checked the logs and it listed AT_Utilis as the fault.

May I see those logs? What exactly happens?

**Comment by allista** [comment]
Closing as inactive. Besides, today have manually checked the current versions of all the mods and found no issues.
