### ISSUE TITLE
1.10 NRE in CraftBrowserDialog.onPipelineFinished

### ISSUE THREAD

**Issue by Freya-Basteln** [allista/AT_Utils#21]
Editor. When I try to add ships, nothing happens when I click on Load after I select a ship.

The good news is there is a workaround. Subassemblies load fine. Probably because you provided your own window to load them up instead of using the stock window like in loading ships.

Here are the logs...  https://www.dropbox.com/s/sgpkqeowglkmjck/log20200707.zip?dl=0

NullReferenceException: Object reference not set to an instance of an object at KSP.UI.Screens.CraftBrowserDialog.onPipelineFinished (ConfigNode n, KSP.UI.Screens.CraftEntry sItem, KSP.UI.Screens.CraftBrowserDialog+LoadType loadType) [0x0005b] in <c168e21ec56346b082f89043e76162e1>:0 at KSP.UI.Screens.CraftBrowserDialog+<>c__DisplayClass126_0.<pipeSelectedItem>b__0 (ConfigNode n) [0x00000] in <c168e21ec56346b082f89043e76162e1>:0 at KSPUpgradePipeline.Process (ConfigNode n, System.String saveName, SaveUpgradePipeline.LoadContext loadContext, Callback`1[T] onSucceed, Callback`2[T,U] onFail) [0x00142] in <c168e21ec56346b082f89043e76162e1>:0 at KSP.UI.Screens.CraftBrowserDialog.pipeSelectedItem (KSP.UI.Screens.CraftEntry sItem, KSP.UI.Screens.CraftBrowserDialog+LoadType loadType) [0x00033] in <c168e21ec56346b082f89043e76162e1>:0 at KSP.UI.Screens.CraftBrowserDialog.ConfirmLoadCraft () [0x00068] in <c168e21ec56346b082f89043e76162e1>:0 at KSP.UI.Screens.CraftBrowserDialog.onButtonLoad () [0x00055] in <c168e21ec56346b082f89043e76162e1>:0

**Comment by allista** [comment]
By accident, the actually is the repository containing the code that is broken. So I've reopened it, but will keep the allista/GroundConstruction#77 as it is affected; there's also a linked issue in allista/Hangar#218
