### ISSUE TITLE
Floating resized parts

### ISSUE THREAD

**Issue by fx-pain** [allista/AT_Utils#7]
For me it looks like AnisotropicPartResizer issue. Parts get offset more and more on some vessel reloads.
When first appeared, I notice that offset was proportional to default part size. Experienced it with space crane and hangar 6 way hab also. I'm fixing it it by editing save file.
It may be related to vessel reroot to some part perpendicular to old root when docking/grabbing.

![screenshot4](https://user-images.githubusercontent.com/33294916/45756447-ee2ac580-bc31-11e8-822b-6c6cf00df41e.png)
![screenshot5](https://user-images.githubusercontent.com/33294916/45756449-ee2ac580-bc31-11e8-8075-de8a084e959b.png)
![screenshot6](https://user-images.githubusercontent.com/33294916/45756450-eec35c00-bc31-11e8-9a20-83012ad3c2a4.png)
![screenshot7](https://user-images.githubusercontent.com/33294916/45756451-eec35c00-bc31-11e8-84e8-4f76e8a0dcdc.png)

**Comment by allista** [comment]
Thanks for the report. Will look into it ASAP.

**Comment by allista** [comment]
BTW, anything in the logs? Exceptions?

**Comment by fx-pain** [comment]
Lots of garbage, but don't see anything relevant.
Trying to reproduce. It may take some time.

**Comment by fx-pain** [comment]
Got the bug consistently with this sequence:
Load save near asteroid - grabbed asteroid - goto space center - warped few hours - goto vessel = offset.

`				name = HangarRadialAdapter1
				cid = 4293859316
				uid = 3914975923
				mid = 3319023015
				persistentId = 1837161644
				launchID = 85
				parent = 0
				position = -1.1464629173278809,-2.9596290588378906,1.1039619445800781
				rotation = -4.13006411E-08,-0.923879623,1.71072845E-08,0.382683456`

`				name = HangarRadialAdapter1
				cid = 4293859316
				uid = 3914975923
				mid = 3319023015
				persistentId = 1837161644
				launchID = 85
				parent = 0
				position = -1.3322162628173828,-3.8807592391967773,1.7790193557739258
				rotation = -4.13006411E-08,-0.923879623,1.71072845E-08,0.382683456`

Nothing new in logs. But just in case:
[KSP - копия (6).log](https://github.com/allista/AT_Utils/files/2397973/KSP.-.6.log)

**Comment by allista** [comment]
Fixed in 57d57d74b622dfa06d22755bd3bd184e70464644
Will be in the next release.
